apiVersion: v1
kind: Secret
metadata:
  name: {{ template "microservices.database-name" . }}
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "microservices.database-name" .)) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $adminUsername := (get $secretData "adminUsername") | default ("admin" | b64enc) }}
  {{- $adminPassword := (get $secretData "adminPassword") | default (randAlphaNum 32 | b64enc) }}
  {{- $cookieAuthSecret := (get $secretData "cookieAuthSecret") | default (randAlphaNum 32 | b64enc) }}
  {{- $erlangCookie := (get $secretData "erlangCookie") | default (randAlphaNum 32 | b64enc) }}
  adminUsername: {{ $adminUsername | quote }}
  adminPassword: {{ $adminPassword | quote }}
  cookieAuthSecret: {{ $cookieAuthSecret | quote }}
  erlangCookie: {{ $erlangCookie | quote }}