
apiVersion: v1
kind: Secret
metadata:
  name: image-pull
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ with .Values.imageCredentials | required "Must provide imageCredentials" }}
    {{- printf "{\"auths\":{\"ghcr.io\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .username .password .email (printf "%s:%s" .username .password | b64enc) | b64enc }}
    {{- end }}