apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
  - hosts:
    - database.{{ .Values.ingress.domain }}
    {{- range $name, $settings := .Values.apps }}
    - {{ $name }}.{{ $.Values.ingress.domain }}
    {{- end }}
    secretName: tls
  rules:
  - host: "database.{{ .Values.ingress.domain | required "ingress.domain is required" }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Release.Name }}-couchdb
            port:
              number: 5984
  {{- range $name, $settings := .Values.apps }}
  - host: "{{ $name }}.{{ $.Values.ingress.domain }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ $name }}
            port:
              number: 80
  {{- end }}