apiVersion: v1
kind: Secret
metadata:
  name: session
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "session") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $sessionSecret := (get $secretData "secret") | default (randAlphaNum 32 | b64enc) }}
  secret: {{ $sessionSecret | quote }}