apiVersion: v2
name: microservices
description: Northroad Craftworks Microservices
version: 0.1.1
dependencies:
  - name: couchdb
    version: 3.6.1
    repository: https://apache.github.io/couchdb-helm