ingress:
  domain: northroad-craftworks.com
  annotations: 
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod

versions:
  inventory: 1.11.1

imagePullSecrets:
  - name: image-pull

allowAnonymous: false

# Google authentication is enabled if a clientId is provided.
googleOauth:
  enable: false
  clientId:
  clientSecret:

# Another config file must provide the credentials.
# imageCredentials:
#   username: someone
#   password: my-super-password
#   email: someone@somewhere.place

couchdb:
  couchdbConfig:
    couchdb:
      uuid: 5920420c-1d39-4514-9b93-71d453826dbc

  clusterSize: 1
  ingress:
    enabled: false

  createAdminSecret: false

  persistentVolume:
    enabled: true
    size: 1Gi

    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "app"
                  operator: In
                  values:
                    - couchdb
            topologyKey: "kubernetes.io/hostname"