name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Semantic Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Semantic Release
        id: semantic-release
        uses: cycjimmy/semantic-release-action@v3.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 19.0.5
          extra_plugins: |
            conventional-changelog-eslint@3.0.9
            semantic-release-helm3@2.3.3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@1.4.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          config: cr.yaml
          charts_dir: .
          release_notes_file: CHANGELOG.md